### ISSUE TITLE
frontend templates not exported?

### ISSUE THREAD

**Issue by hagerp** [IchHabRecht/mask_export#116]
Hi,

the plugin only exports the standard templates not the defined one in for example
fileadmin/templates/content/

**Comment by IchHabRecht** [comment]
Hi @hagerp,

Yes, that is right, because those templates cannot be used for the export. Due to different data initialization in typoscript (to remove / prevent the mask dependency) slightly other variables names need to be used. This is way the export "shows" how it works in its own example templates.

**Comment by IchHabRecht** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience a problem.
