### ISSUE TITLE
Update to Mask 7

### ISSUE THREAD

**Issue by heroheman** [IchHabRecht/mask_export#179]
Now that a new version of Mask has been released, compatibility with Mask Export should be ensured. 

https://docs.typo3.org/p/mask/mask/master/en-us/ChangeLog/7.0/Index.html

**Comment by DTM-TYPO3** [comment]
Hi there,
are there any plans to adapt Mask Export for the new Mask V7? The EXT has been a great help to me so far and I would be happy if it were also available in the current version.
Thanks in advance
Stefanie

**Comment by MarkusBausK** [comment]
Is there a plan to continue this project? We're very insecure right now. We don't use mask in live projects and we would be very happy to be able to continue using mask_export in the future, because it is now an essential part of our workflow. We would also support the project financially. It would be good to know if there are certain technical or personal reasons that are hindering or even stopping further development. Everyone should respect that, but it would be good to know if there's any plan.

Thank you so far and in advance!

**Comment by georgringer** [comment]
Related a bit https://github.com/IchHabRecht/mask_export/pull/185
